### ISSUE TITLE
Periods in labels cause eleasticsearch to break

### ISSUE THREAD

**Issue by cookandy** [digital-wonderland/docker-logstash-forwarder#26] opened 2015-12-21 18:26 UTC
When starting the docker-logstash-forwarder, periods appear in the labels as shown below:

```
"files": [
 {
   "paths": [
     "/var/lib/docker/containers/b6776b586eadf879fc5722e33adb0b569efb0fa846801e5137f43f1c64643e4f/b6776b586eadf879fc5722e33adb0b569efb0fa846801e5137f43f1c64643e4f-json.log"
   ],
   "fields": {
     "codec": "json",
     "docker/hostname": "b6776b586ead",
     "docker/id": "b6776b586eadf879fc5722e33adb0b569efb0fa846801e5137f43f1c64643e4f",
     "docker/image": "acook/logstash-forwarder:latest",
     "docker/label/License": "GPLv2",
     "docker/label/Vendor": "CentOS",
     "docker/label/com.docker.compose.config-hash": "2131f95c162c74958e7f131bac9dd20f1795e5d5e96d12045675f5e0d83d85a6",
     "docker/label/com.docker.compose.container-number": "1",
     "docker/label/com.docker.compose.oneoff": "False",
     "docker/label/com.docker.compose.project": "dockerlogstashforwarder",
     "docker/label/com.docker.compose.service": "logstash-forwarder",
     "docker/label/com.docker.compose.version": "1.5.1",
     "docker/name": "/dockerlogstashforwarder_logstash-forwarder_1",
     "type": "docker"
   }
 },

```

This causes elasticsearch to throw errors.  Same as issue https://github.com/digital-wonderland/docker-logstash-forwarder/issues/20

**Comment by digital-wonderland** [comment] 2015-12-27 10:48
This was the expected behaviour but should work now since https://github.com/digital-wonderland/docker-logstash-forwarder/pull/24 got merged.

**Closed by digital-wonderland** 2015-12-27 10:48 UTC

**Comment by cookandy** [comment] 2015-12-28 15:08
Yes, it works great now - thanks!  I think my problem was the binary wasn't updated.  :)
